export const INFRASTRUCTURE_ERROR_CODES = {
	CONFIG: {
		VALIDATION_FAILED: "SYSTEM.CONFIG.VALIDATION_FAILED",
		NOT_INITIALIZED: "SYSTEM.CONFIG.NOT_INITIALIZED",
	},
	AUTH: {
		STRATEGY_NOT_IMPLEMENTED: "SYSTEM.AUTH.STRATEGY_NOT_IMPLEMENTED",
	},
} as const;

export type InfrastructureErrorCode =
	| (typeof INFRASTRUCTURE_ERROR_CODES.CONFIG)[keyof typeof INFRASTRUCTURE_ERROR_CODES.CONFIG]
	| (typeof INFRASTRUCTURE_ERROR_CODES.AUTH)[keyof typeof INFRASTRUCTURE_ERROR_CODES.AUTH];
