export const MIDDLEWARE_ERROR_CODES = {
	COMMON: {
		UNEXPECTED: "SYSTEM.MIDDLEWARE.UNEXPECTED",
		UNKNOWN_ERROR: "SYSTEM.UNKNOWN_ERROR",
	},
	TENANT_AUTH: {
		HEADER_MISSING: "SYSTEM.MIDDLEWARE.TENANT_HEADER_MISSING",
	},
	JWT_AUTH: {
		AUTHENTICATION_FAILED: "SYSTEM.MIDDLEWARE.JWT_AUTHENTICATION_FAILED",
	},
} as const;

export type MiddlewareErrorCode =
	| (typeof MIDDLEWARE_ERROR_CODES.COMMON)[keyof typeof MIDDLEWARE_ERROR_CODES.COMMON]
	| (typeof MIDDLEWARE_ERROR_CODES.TENANT_AUTH)[keyof typeof MIDDLEWARE_ERROR_CODES.TENANT_AUTH]
	| (typeof MIDDLEWARE_ERROR_CODES.JWT_AUTH)[keyof typeof MIDDLEWARE_ERROR_CODES.JWT_AUTH];
