/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 認証中のユーザー自身と所属テナントの一覧を取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["v1GetMeResponseSchema"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description テナントのプロジェクト一覧を取得する（検索・ページネーション） */
        get: {
            parameters: {
                query?: {
                    search?: components["schemas"]["v1GetProjectsQuerySchema.search"];
                    page?: components["schemas"]["v1GetProjectsQuerySchema.page"];
                    limit?: components["schemas"]["v1GetProjectsQuerySchema.limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["v1GetProjectsResponseSchema"];
                    };
                };
            };
        };
        put?: never;
        /** @description プロジェクトを作成する */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["v1CreateProjectBodySchema"];
                };
            };
            responses: {
                /** @description Created Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["v1ProjectResponseSchema"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description プロジェクトを 1 件取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: components["schemas"]["v1ProjectIdParamsSchema.projectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["v1ProjectResponseSchema"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** @description プロジェクトを削除する（論理削除） */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: components["schemas"]["v1ProjectIdParamsSchema.projectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** @description プロジェクトを部分更新する */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: components["schemas"]["v1ProjectIdParamsSchema.projectId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["v1UpdateProjectBodySchema"];
                };
            };
            responses: {
                /** @description Success Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["v1ProjectResponseSchema"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "v1GetMeResponseSchema.id": string;
        "v1GetMeResponseSchema.emailAddress": string;
        "v1GetMeResponseSchema.name": string;
        "v1GetMeResponseSchema.memberships": {
            membershipId: string;
            tenantId: string;
            /** @enum {string} */
            role: "ADMIN" | "MEMBER" | "GUEST";
        }[];
        v1GetMeResponseSchema: {
            id: components["schemas"]["v1GetMeResponseSchema.id"];
            emailAddress: components["schemas"]["v1GetMeResponseSchema.emailAddress"];
            name: components["schemas"]["v1GetMeResponseSchema.name"];
            memberships: components["schemas"]["v1GetMeResponseSchema.memberships"];
        };
        "v1ProjectResponseSchema.id": string;
        "v1ProjectResponseSchema.tenantId": string;
        "v1ProjectResponseSchema.name": string;
        "v1ProjectResponseSchema.description": string | null;
        v1ProjectResponseSchema: {
            id: components["schemas"]["v1ProjectResponseSchema.id"];
            tenantId: components["schemas"]["v1ProjectResponseSchema.tenantId"];
            name: components["schemas"]["v1ProjectResponseSchema.name"];
            description: components["schemas"]["v1ProjectResponseSchema.description"];
        };
        "v1CreateProjectBodySchema.name": string;
        "v1CreateProjectBodySchema.description": string | null;
        v1CreateProjectBodySchema: {
            name: components["schemas"]["v1CreateProjectBodySchema.name"];
            description?: components["schemas"]["v1CreateProjectBodySchema.description"];
        };
        "v1GetProjectsResponseSchema.projects": {
            id: string;
            name: string;
            description: string | null;
            createdAt: string;
            updatedAt: string;
        }[];
        "v1GetProjectsResponseSchema.pagination": {
            currentPage: number;
            totalPages: number;
            totalCount: number;
            hasNext: boolean;
            hasPrevious: boolean;
        };
        v1GetProjectsResponseSchema: {
            projects: components["schemas"]["v1GetProjectsResponseSchema.projects"];
            pagination: components["schemas"]["v1GetProjectsResponseSchema.pagination"];
        };
        "v1GetProjectsQuerySchema.search": string;
        "v1GetProjectsQuerySchema.page": number;
        "v1GetProjectsQuerySchema.limit": number;
        /** Format: uuid */
        "v1ProjectIdParamsSchema.projectId": string;
        "v1UpdateProjectBodySchema.name": string;
        "v1UpdateProjectBodySchema.description": string | null;
        v1UpdateProjectBodySchema: {
            name?: components["schemas"]["v1UpdateProjectBodySchema.name"];
            description?: components["schemas"]["v1UpdateProjectBodySchema.description"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
