export const MEMBERSHIP_ERROR_CODES = {
	COMMON: {
		NOT_FOUND: "MEMBERSHIP.COMMON.NOT_FOUND",
		FORBIDDEN: "MEMBERSHIP.COMMON.FORBIDDEN",
	},
	VALIDATION: {
		INVALID_ROLE: "MEMBERSHIP.VALIDATION.INVALID_ROLE",
	},
} as const;

export type MembershipErrorCode =
	| (typeof MEMBERSHIP_ERROR_CODES.COMMON)[keyof typeof MEMBERSHIP_ERROR_CODES.COMMON]
	| (typeof MEMBERSHIP_ERROR_CODES.VALIDATION)[keyof typeof MEMBERSHIP_ERROR_CODES.VALIDATION];
