export const PROJECT_ERROR_CODES = {
	ACCESS: {
		NOT_FOUND: "PROJECT.ACCESS.NOT_FOUND",
		NOT_AUTHORIZED: "PROJECT.ACCESS.NOT_AUTHORIZED",
	},
	VALIDATION: {
		NAME_EMPTY: "PROJECT.VALIDATION.NAME_EMPTY",
		NAME_TOO_LONG: "PROJECT.VALIDATION.NAME_TOO_LONG",
		DESCRIPTION_TOO_LONG: "PROJECT.VALIDATION.DESCRIPTION_TOO_LONG",
		DUPLICATE_NAME: "PROJECT.VALIDATION.DUPLICATE_NAME",
		COUNT_LIMIT_EXCEEDED: "PROJECT.VALIDATION.COUNT_LIMIT_EXCEEDED",
		ALREADY_DELETED: "PROJECT.VALIDATION.ALREADY_DELETED",
	},
} as const;

export type ProjectErrorCode =
	| (typeof PROJECT_ERROR_CODES.ACCESS)[keyof typeof PROJECT_ERROR_CODES.ACCESS]
	| (typeof PROJECT_ERROR_CODES.VALIDATION)[keyof typeof PROJECT_ERROR_CODES.VALIDATION];
