export const TENANT_ERROR_CODES = {
	COMMON: {
		NOT_FOUND: "TENANT.COMMON.NOT_FOUND",
	},
	VALIDATION: {
		NAME_EMPTY: "TENANT.VALIDATION.NAME_EMPTY",
		NAME_TOO_LONG: "TENANT.VALIDATION.NAME_TOO_LONG",
	},
} as const;

export type TenantErrorCode =
	| (typeof TENANT_ERROR_CODES.COMMON)[keyof typeof TENANT_ERROR_CODES.COMMON]
	| (typeof TENANT_ERROR_CODES.VALIDATION)[keyof typeof TENANT_ERROR_CODES.VALIDATION];
