export const USER_ERROR_CODES = {
	COMMON: {
		NOT_FOUND: "USER.COMMON.NOT_FOUND",
	},
	VALIDATION: {
		ID_EMPTY: "USER.VALIDATION.ID_EMPTY",
		INVALID_EMAIL: "USER.VALIDATION.INVALID_EMAIL",
	},
} as const;

export type UserErrorCode =
	| (typeof USER_ERROR_CODES.COMMON)[keyof typeof USER_ERROR_CODES.COMMON]
	| (typeof USER_ERROR_CODES.VALIDATION)[keyof typeof USER_ERROR_CODES.VALIDATION];
