class SUMMARY_JOB_ERROR_CODES:  # noqa: N801
    class ACCESS:  # noqa: N801
        NOT_FOUND = "SUMMARY_JOB.ACCESS.NOT_FOUND"
        NOT_AUTHORIZED = "SUMMARY_JOB.ACCESS.NOT_AUTHORIZED"

    class VALIDATION:  # noqa: N801
        TEXT_EMPTY = "SUMMARY_JOB.VALIDATION.TEXT_EMPTY"
        TEXT_TOO_LONG = "SUMMARY_JOB.VALIDATION.TEXT_TOO_LONG"
        INVALID_TRANSITION = "SUMMARY_JOB.VALIDATION.INVALID_TRANSITION"


class USER_ERROR_CODES:  # noqa: N801
    class LOGIN:  # noqa: N801
        NOT_AUTHENTICATED = "USER.LOGIN.NOT_AUTHENTICATED"


class VALIDATION_ERROR_CODES:  # noqa: N801
    class REQUEST:  # noqa: N801
        INVALID = "VALIDATION.REQUEST.INVALID"
        TENANT_HEADER_MISSING = "VALIDATION.REQUEST.TENANT_HEADER_MISSING"


class DATABASE_ERROR_CODES:  # noqa: N801
    class REPOSITORY:  # noqa: N801
        ACCESS_ERROR = "DATABASE.REPOSITORY.ACCESS_ERROR"
        OPTIMISTIC_LOCK_CONFLICT = "DATABASE.REPOSITORY.OPTIMISTIC_LOCK_CONFLICT"


class INFRASTRUCTURE_ERROR_CODES:  # noqa: N801
    class EXTERNAL_SERVICE:  # noqa: N801
        ERROR = "INFRASTRUCTURE.EXTERNAL_SERVICE.ERROR"

    class CONFIG:  # noqa: N801
        NOT_INITIALIZED = "INFRASTRUCTURE.CONFIG.NOT_INITIALIZED"


class SYSTEM_ERROR_CODES:  # noqa: N801
    INTERNAL_ERROR = "SYSTEM.INTERNAL_ERROR"
    UNEXPECTED_ERROR = "SYSTEM.UNEXPECTED_ERROR"
    DOMAIN_RULE_VIOLATED = "SYSTEM.DOMAIN_RULE_VIOLATED"
