from src.shared.errors.codes import (
    DATABASE_ERROR_CODES,
    INFRASTRUCTURE_ERROR_CODES,
    SUMMARY_JOB_ERROR_CODES,
    SYSTEM_ERROR_CODES,
    USER_ERROR_CODES,
    VALIDATION_ERROR_CODES,
)
from src.shared.errors.messages import MESSAGE_KEYS
from src.shared.errors.types import ErrorDefinition

ERROR_DEFINITIONS: dict[str, ErrorDefinition] = {
    SUMMARY_JOB_ERROR_CODES.ACCESS.NOT_FOUND: ErrorDefinition(
        404, MESSAGE_KEYS.SUMMARY_JOB.NOT_FOUND, False, "warning"
    ),
    SUMMARY_JOB_ERROR_CODES.ACCESS.NOT_AUTHORIZED: ErrorDefinition(
        403, MESSAGE_KEYS.SUMMARY_JOB.NOT_AUTHORIZED, False, "warning"
    ),
    SUMMARY_JOB_ERROR_CODES.VALIDATION.TEXT_EMPTY: ErrorDefinition(
        400, MESSAGE_KEYS.SUMMARY_JOB.TEXT_EMPTY, False, "warning"
    ),
    SUMMARY_JOB_ERROR_CODES.VALIDATION.TEXT_TOO_LONG: ErrorDefinition(
        400, MESSAGE_KEYS.SUMMARY_JOB.TEXT_TOO_LONG, False, "warning"
    ),
    SUMMARY_JOB_ERROR_CODES.VALIDATION.INVALID_TRANSITION: ErrorDefinition(
        409, MESSAGE_KEYS.SUMMARY_JOB.INVALID_TRANSITION, False, "warning"
    ),
    USER_ERROR_CODES.LOGIN.NOT_AUTHENTICATED: ErrorDefinition(
        401, MESSAGE_KEYS.USER.NOT_AUTHENTICATED, False, "warning"
    ),
    VALIDATION_ERROR_CODES.REQUEST.INVALID: ErrorDefinition(
        422, MESSAGE_KEYS.VALIDATION.REQUEST_INVALID, False, "warning"
    ),
    VALIDATION_ERROR_CODES.REQUEST.TENANT_HEADER_MISSING: ErrorDefinition(
        400, MESSAGE_KEYS.VALIDATION.TENANT_HEADER_MISSING, False, "warning"
    ),
    DATABASE_ERROR_CODES.REPOSITORY.ACCESS_ERROR: ErrorDefinition(
        503, MESSAGE_KEYS.SYSTEM.DATABASE_ERROR, True, "error"
    ),
    DATABASE_ERROR_CODES.REPOSITORY.OPTIMISTIC_LOCK_CONFLICT: ErrorDefinition(
        409, MESSAGE_KEYS.SYSTEM.OPTIMISTIC_LOCK_CONFLICT, True, "warning"
    ),
    INFRASTRUCTURE_ERROR_CODES.EXTERNAL_SERVICE.ERROR: ErrorDefinition(
        503, MESSAGE_KEYS.SYSTEM.EXTERNAL_SERVICE_ERROR, True, "error"
    ),
    INFRASTRUCTURE_ERROR_CODES.CONFIG.NOT_INITIALIZED: ErrorDefinition(
        500, MESSAGE_KEYS.SYSTEM.CONFIG_NOT_INITIALIZED, False, "error"
    ),
    SYSTEM_ERROR_CODES.INTERNAL_ERROR: ErrorDefinition(500, MESSAGE_KEYS.SYSTEM.INTERNAL_ERROR, False, "error"),
    SYSTEM_ERROR_CODES.UNEXPECTED_ERROR: ErrorDefinition(500, MESSAGE_KEYS.SYSTEM.UNEXPECTED_ERROR, False, "error"),
    SYSTEM_ERROR_CODES.DOMAIN_RULE_VIOLATED: ErrorDefinition(
        422, MESSAGE_KEYS.SYSTEM.DOMAIN_RULE_VIOLATED, False, "warning"
    ),
}
