/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ヘルスチェック */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/v1/protected/summary-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 要約ジョブを作成する（非同期）
         * @description ジョブを受け付けてすぐ返す。結果は GET /summary-jobs/{job_id} で取得する。
         */
        post: operations["create_summary_job_api_ai_v1_protected_summary_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/v1/protected/summary-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 要約ジョブの状態と結果を取得する */
        get: operations["get_summary_job_api_ai_v1_protected_summary_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreateSummaryJobBodySchema */
        CreateSummaryJobBodySchema: {
            /**
             * Projectid
             * Format: uuid
             */
            projectId: string;
            /** Text */
            text: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @description サービスの状態
             */
            status: string;
        };
        /**
         * JobStatus
         * @description ジョブの状態。遷移は pending → processing → completed | failed の一方向.
         * @enum {string}
         */
        JobStatus: "pending" | "processing" | "completed" | "failed";
        /**
         * SummaryJobResponseSchema
         * @description レスポンスの形。JSON は camelCase（alias）、Python は snake_case.
         */
        SummaryJobResponseSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenantid
             * Format: uuid
             */
            tenantId: string;
            /**
             * Projectid
             * Format: uuid
             */
            projectId: string;
            status: components["schemas"]["JobStatus"];
            /** Summary */
            summary?: string | null;
            /** Errormessage */
            errorMessage?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_summary_job_api_ai_v1_protected_summary_jobs_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSummaryJobBodySchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryJobResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_job_api_ai_v1_protected_summary_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryJobResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
